name: Generate Blog Post

on:
  schedule:
    # Spuštění každý den v 9:00 českého času (7:00 UTC)
    - cron: '0 7 * * *'
  # Umožní manuální spuštění
  workflow_dispatch:

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Install script dependencies
        run: npm install openai axios gray-matter
      
      - name: Generate blog post
        run: node scripts/generate-blog-post.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add content/posts/
          git add public/images/blog/
          git commit -m "Add new blog post (auto-generated)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 